### ISSUE TITLE
Unexpected differences in (long) cloudwatch alarm descriptions

### ISSUE THREAD

**Issue by skx** [molecule-man/stack-assembly#5]
I've got a bunch of stacks which report differences when running `stas diff`, but when I run `stas sync` no changes are deployed.

So far these seem to be 100% related to cloudwatch alarms, and the differences seem to be in the description fields.

Here's the output of `stas diff`:

```
$ ../stas diff --nocolor --profile tmp
--- old/prod-ftcat1
+++ new/prod-ftcat1
@@ -420,11 +420,12 @@
   ftcat1CPUCreditBalance:
     Properties:
       ActionsEnabled: true
       AlarmActions:
         - !ImportValue 'EmailWarningTopic'
-      AlarmDescription: The number of earned CPU credits that an instance has accrued since it was launched or started.
+      AlarmDescription: The number of earned CPU credits that an instance has accrued
+        since it was launched or started.
       ComparisonOperator: LessThanThreshold
       Dimensions:
         - Name: InstanceId
           Value: !Ref 'ftcat1'
       EvaluationPeriods: '30'

--- old/prod-ftcat2
+++ new/prod-ftcat2
@@ -420,11 +420,12 @@
   ftcat2CPUCreditBalance:
     Properties:
       ActionsEnabled: true
       AlarmActions:
         - !ImportValue 'EmailWarningTopic'
-      AlarmDescription: The number of earned CPU credits that an instance has accrued since it was launched or started.
+      AlarmDescription: The number of earned CPU credits that an instance has accrued
+        since it was launched or started.
       ComparisonOperator: LessThanThreshold
       Dimensions:
         - Name: InstanceId
           Value: !Ref 'ftcat2'
       EvaluationPeriods: '30'
```

When I run the "sync" operation those differences disappear:

```
$ ../stas sync --nocolor --profile tmp
[prod-ovpn] Synchronizing template
[prod-ovpn] No changes to be synchronized
[prod-online] Synchronizing template
[prod-online] No changes to be synchronized
[prod-gitlab-runner-role] Synchronizing template
[prod-gitlab-runner-role] No changes to be synchronized
[prod-ftcat1] Synchronizing template
[prod-ftcat1] No changes to be synchronized
[prod-ftcat2] Synchronizing template
[prod-ftcat2] No changes to be synchronized
```

I suspect that the issue here is how the cloudformation template itself is generated if the description is too long.  Instead of being a single string it is split into two lines:

```
      AlarmActions:
        - !ImportValue 'EmailWarningTopic'
      AlarmDescription: The number of earned CPU credits that an instance has accrued
        since it was launched or started.
      ComparisonOperator: LessThanThreshold
      Dimensions:
```

So this is not truely a bug, neither with your tool, nor with the difflib library you're using:

* https://github.com/pmezard/go-difflib/blob/master/difflib/difflib.go

That said it seems there's not an obvious workaround, short of reducing the length of the alarm descriptions.   I  just file this issue in case something sprints to your mind as a better alternative?

**Comment by molecule-man** [comment]
Thanks for reporting this :+1: . 
the reason is that these two yamls are equivalent:
```yaml
key: some value
```
```yaml
key: some
  value
```
it is like that because of [the way yaml treats newlines](https://yaml-multiline.info/). difflib just compares two strings without "knowing" that the newline will be ignored when yaml  is parsed by cloudformation.
I think I know what might fix this. Let me think a bit if I can make `diff` a bit smarter and take into account the file format of template.

**Comment by skx** [comment]
Yeah I guess towards the tail end of my ramble I was saying it wasn't really your fault, but a consequence of the wrapped and unwrapped lines being identical from YAMLs point of view.

I've solved my immediate issue by reducing the length of alarm-descriptions to avoid the wrapping.  (In my case the cloudformation  files are produced by the python troposphere library, and I couldn't find an option there to prevent it.  Though I guess I could have written a post-processor to update post-generation).

It does feel like this is something that could be handled to avoid the false positive, but at the same time there are literal differences so I could accept any argument you made to leave the behaviour alone if the complexity of trying to detect it was too hard!

**Comment by molecule-man** [comment]
oops auto-closed by accident from git commit. Reopening.

**Comment by molecule-man** [comment]
I updated diff command with a check if unmarshalled yamls are identical in https://github.com/molecule-man/stack-assembly/commit/41524b5d881908b72ba9bd71afe19152e1bd8da4#diff-7189d4fb505d38d390818a979c5a4572f68fed5b8ff5c03fc55c6088f6cd4414R105. In my tests it fixed the issue.

The fix was released in https://github.com/molecule-man/stack-assembly/releases/tag/v0.5.1.

@skx I'm closing the issue. Feel free to reopen it if the fix doesn't work for you.
